# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres
  cache:
    image: redis:latest
  web:
    image: maykinmedia/zds-token-issuer
    environment:
      - DJANGO_SETTINGS_MODULE=token_issuer.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
