name: ci-build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: maykinmedia/zds-token-issuer
  DJANGO_SETTINGS_MODULE: token_issuer.conf.ci
  SECRET_KEY: dummy
  DB_USER: postgres
  DB_PASSWORD: ''
  DEPLOYMENT: token_issuer

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: ['10', '11', '12']

    name: Tests (PG ${{ matrix.postgres }})

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Install dependencies
        run: pip install -r requirements/ci.txt codecov

      - name: Build frontend
        run: |
          npm ci
          npm run build
      - name: Run python tests
        run: |
          python src/manage.py collectstatic --noinput --link
          coverage run src/manage.py test src

      - name: Run javascript tests
        run: npm run test

      - name: Publish coverage report
        uses: codecov/codecov-action@v1

  docker:
    runs-on: ubuntu-latest
    name: Docker image build

    steps:
      - uses: actions/checkout@v2
      - name: Determine tag/commit hash
        id: vars
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name (if present at all)
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo ::set-output name=tag::${VERSION}
          echo ::set-output name=git_hash::${GITHUB_SHA}
      - name: Build the Docker image
        run: |
          docker build . \
          --build-arg COMMIT_HASH=${{ steps.vars.outputs.git_hash }}

  publish:
    needs:
      - tests
      - docker

    name: Push Docker image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # exclude PRs/forks

    steps:
      - uses: actions/checkout@v2
      - name: Publish latest image
        env: # Or as an environment variable
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$BRANCH" == "master" ]; then
          bash bin/docker_push.sh latest
          fi

      - name: Publish tagged image
        env: # Or as an environment variable
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          TAG=$(git name-rev --tags --name-only $(git rev-parse HEAD))
          if [ "$TAG" != "undefined" ]; then
          bash bin/docker_push.sh $TAG
          fi
